# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Buyer Guide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buyer Guide
  pod 'SwiftSoup'
  pod 'Kingfisher', '~> 7.0'

  # target 'Buyer GuideTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'Buyer GuideUITests' do
  #   # Pods for testing
  # end

end
